[package]
name = "gpu-screen-recorder-motif"
type = "executable"
version = "5.7.9"
platforms = ["posix"]

[config]
ignore_dirs = ["build"]
error_on_warning = "false"

[dependencies]
xm = ">=2.3"
xt = "1"
x11 = "1"
xmu = "1"
xpm = "3"
xext = "1"
