[package]
name = "gpu-screen-recorder-gtk"
type = "executable"
version = "3.0.0"
platforms = ["posix"]

[config]
error_on_warning = "true"

[dependencies]
gtk+-3.0 = "3"
x11 = "1"
xrandr = "1"
libpulse = ">=13"
libdrm = ">=2"
wayland-egl = ">=15"
wayland-client = ">=1"